# For per pipeline config, check docs: https://www.elastic.co/guide/en/logstash/current/logstash-settings-file.html

- pipeline.id: main
  path.config: "/usr/share/logstash/pipeline/main.conf"
  queue.type: memory

#- pipeline.id: second_pipeline
#  path.config: "/usr/share/logstash/pipeline/second.conf"
#  queue.type: persisted
#  pipeline.batch.size: 125
#  queue.page_capacity: 50mb

###########################
#
# Biometro.earth configurations
#
###########################


#############################################
# Tochtli pipeline to count and receive all data from all projects.

- pipeline.id: tochtli
  path.config: "/usr/share/logstash/pipeline/tochtli.conf"


##############################
# Taxa Pipelines for Zambia Project

- pipeline.id: bed_occurrences_pipeline
  path.config: "/usr/share/logstash/pipeline/bed_occurrences.conf"
  queue.type: memory

- pipeline.id: bed_taxa_pipeline
  path.config: "/usr/share/logstash/pipeline/bed_taxa.conf"
  queue.type: memory